-- AlterTable
ALTER TABLE `user` MODIFY `col1` BLOB NULL,
    MODIFY `col2` LONGBLOB NULL,
    MODIFY `col3` TINYBLOB NULL,
    MODIFY `col4` MEDIUMBLOB NULL,
    MODIFY `col5` BINARY(100) NULL,
    MODIFY `col6` VARBINARY(100) NULL;
